workflows:
  android-release:
    name: Android Build
    environment:
      node: 22
      java: 17
    scripts:
      - npm install
      - npm run build
      - rm -rf android
      - npx cap add android
      - npx cap copy
      - chmod +x android/gradlew
      - cd android && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
