workflows:
  android-release:
    name: Android Build
    environment:
      node: 22
      java: 17
    scripts:
      - npm install
      - npm run build
      - rm -rf android
      - npx cap add android
      - npx cap copy
      - echo "org.gradle.java.home=/usr/lib/jvm/java-17-openjdk-amd64" >> android/gradle.properties
      - cd android && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
