name: Build APK
on: [push, workflow_dispatch]
jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with: 
          node-version: 22 # تم التحديث هنا لحل مشكلة Capacitor
          
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with: 
          distribution: 'temurin' 
          java-version: '21'
      
      - name: Build App
        run: |
          npm install
          npm run build
          # إضافة مكاتب كاباسيتور الأساسية لضمان وجودها
          npm i @capacitor/core @capacitor/android
          npx cap sync android || (npx cap add android && npx cap sync android)
          
      - name: Build Android APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-offline-translator
          path: android/app/build/outputs/apk/debug/app-debug.apk
